# Welcome to Jekyll!
#

# Site settings
title: Multi Disciplinary Solutions
description: |
    When you need to find that which you wished existed, but can't
owner: Owner # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: multidisciplinarysolutionsco@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://voidnologo.github.io/multidisciplinarysolutionsco.site/" # the base hostname & protocol for your site
social:
  github: https://github.com/voidnologo
  email: /contact/

# Build settings
markdown: kramdown
#sass:
#  style: compressed
